Complete 1st module
js-tasks-ru/jsbasic-20220113_breezeineua pull request #2
Opened 2022-01-24 21:07 UTC by kateriii

2022-01-24 21:08 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-25 11:41 UTC, SinimaWath requested changes

2022-01-25 11:41 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  multi = 1;
Это не создание переменной - используй: `const` или `let`

2022-01-25 11:41 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
Можно упростить до: `lowerStr.includes("1xbet") || lowerStr.includes("xxx")`

2022-01-25 21:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-25 21:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-01-26 11:02 UTC, SinimaWath approved these changes
все ок!

2022-01-26 11:02 UTC, merged